const STUDENT_REPORT_PROMPT_VERSION = "student-report-draft-v1";

function safeArray(value) {
  return Array.isArray(value) ? value : [];
}

function cleanEvidenceItem(item = {}) {
  return {
    evidence_type: item.evidence_type ?? null,
    statement: item.statement ?? "",
    explanation: item.explanation ?? null,
    confidence: item.confidence ?? null,
    session_id: item.session_id ?? null,
    curriculum_node_id: item.curriculum_node_id ?? null,
  };
}

function cleanActionItem(item = {}) {
  return {
    action_origin: item.action_origin ?? null,
    action_type: item.action_type ?? null,
    title: item.title ?? "",
    description: item.description ?? null,
    target_role: item.target_role ?? null,
    confidence: item.confidence ?? null,
    session_id: item.session_id ?? null,
  };
}

function cleanSessionItem(item = {}) {
  return {
    session_id: item.session_id ?? null,
    date: item.date ?? null,
    session_title: item.session_title ?? null,
    offering_name: item.offering_name ?? null,
    tutor_name: item.tutor_name ?? null,
    duration_minutes: item.duration_minutes ?? null,
    attendance_status: item.attendance_status ?? null,
    session_summary: item.session_summary ?? null,
  };
}

export function buildPenEStudentReportPackage(report) {
  if (!report) {
    throw new Error("Report is required.");
  }

  if (report.subject_type !== "student") {
    throw new Error(
      "Pen-E Student Report Drafting only supports student reports."
    );
  }

  const snapshot = report.data_snapshot ?? {};

  const student = snapshot.student ?? {};
  const reportingPeriod = snapshot.reporting_period ?? {
    type: report.report_type ?? null,
    start: report.period_start ?? null,
    end: report.period_end ?? null,
  };

  return {
    package_type: "aeos_pen_e_student_report_draft",
    package_version: "1.0",
    prompt_version: STUDENT_REPORT_PROMPT_VERSION,

    report_context: {
      report_id: report.report_id,
      report_type: report.report_type,
      report_title: report.report_title,
      report_status: report.report_status,
      period_start: report.period_start,
      period_end: report.period_end,
    },

    student: {
      student_id: student.student_id ?? report.student_id ?? null,
      first_name: student.first_name ?? null,
      last_name: student.last_name ?? null,
      display_name: student.display_name ?? null,
      school: student.school ?? null,
    },

    reporting_period: reportingPeriod,

    session_metrics: snapshot.session_metrics ?? {},

    attendance: snapshot.attendance ?? {},

    offerings: safeArray(snapshot.offerings),

    tutors: safeArray(snapshot.tutors),

    sessions: safeArray(snapshot.sessions).map(cleanSessionItem),

    reviewed_learning_evidence: safeArray(
      snapshot.learning_evidence
    ).map(cleanEvidenceItem),

    reviewed_actions: safeArray(snapshot.actions).map(cleanActionItem),

    reviewed_curriculum_matches: safeArray(
      snapshot.curriculum?.reviewed_matches
    ),

    instructions: getStudentReportDraftInstructions(),
  };
}

export function getStudentReportDraftInstructions() {
  return {
    role:
      "You are Pen-E, the educational intelligence assistant for A's Online / AEOS.",

    task:
      "Draft a parent/student-facing student progress report using only the supplied AEOS report package.",

    evidence_rules: [
      "Use only information contained in this package.",
      "Do not invent learning, progress, behaviour, attendance, curriculum coverage, recommendations, or achievements.",
      "Tutor explanation alone is not evidence that the student understands a concept.",
      "Distinguish independent success from prompted, guided, partial, or uncertain understanding.",
      "Do not convert one correct response into a claim of mastery.",
      "Repeated evidence may be synthesized into a broader pattern when the supplied evidence supports it.",
      "Preserve uncertainty where the evidence is limited.",
      "Use reviewed evidence and reviewed actions as the authoritative learning evidence supplied for this report.",
      "Do not manufacture curriculum claims.",
      "If reviewed curriculum matches are empty, return an empty curriculum_progress array.",
    ],

    writing_rules: [
      "Write for a parent and student audience.",
      "Use clear, professional, encouraging educational language.",
      "Be constructive without exaggerating progress.",
      "Do not expose database terminology, IDs, confidence scores, Pen-E internals, review statuses, or raw transcript excerpts.",
      "Do not mention that the report was generated by AI.",
      "Synthesize evidence rather than listing every evidence item.",
      "Avoid repetitive statements across sections.",
      "Areas for development should describe skills or concepts that need continued attention, not criticize the student.",
      "Follow-up priorities should be practical and supported by the supplied evidence or reviewed actions.",
      "The closing comment should give a balanced summary of progress and next steps.",
    ],

    output_rules: [
      "Return valid JSON only.",
      "Do not include Markdown.",
      "Do not include commentary before or after the JSON.",
      "Use exactly the required output structure.",
      "Do not add additional top-level fields.",
    ],

    required_output: {
      report_version: "student-content-v1",
      overview: {
        headline: "",
        summary: "",
      },
      learning_highlights: [],
      areas_for_development: [],
      follow_up_priorities: [],
      curriculum_progress: [],
      closing_comment: "",
    },
  };
}

function isPlainObject(value) {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
  );
}

function isStringArray(value) {
  return (
    Array.isArray(value) &&
    value.every((item) => typeof item === "string")
  );
}

export function validatePenEStudentReportDraft(value) {
  const errors = [];

  if (!isPlainObject(value)) {
    return {
      valid: false,
      errors: ["The Pen-E response must be a JSON object."],
    };
  }

  const allowedTopLevelKeys = [
    "report_version",
    "overview",
    "learning_highlights",
    "areas_for_development",
    "follow_up_priorities",
    "curriculum_progress",
    "closing_comment",
  ];

  const extraKeys = Object.keys(value).filter(
    (key) => !allowedTopLevelKeys.includes(key)
  );

  if (extraKeys.length > 0) {
    errors.push(
      `Unexpected fields: ${extraKeys.join(", ")}`
    );
  }

  if (value.report_version !== "student-content-v1") {
    errors.push(
      'report_version must be "student-content-v1".'
    );
  }

  if (!isPlainObject(value.overview)) {
    errors.push("overview must be an object.");
  } else {
    if (typeof value.overview.headline !== "string") {
      errors.push("overview.headline must be a string.");
    }

    if (typeof value.overview.summary !== "string") {
      errors.push("overview.summary must be a string.");
    }
  }

  if (!isStringArray(value.learning_highlights)) {
    errors.push("learning_highlights must be an array of strings.");
  }

  if (!isStringArray(value.areas_for_development)) {
    errors.push(
      "areas_for_development must be an array of strings."
    );
  }

  if (!isStringArray(value.follow_up_priorities)) {
    errors.push(
      "follow_up_priorities must be an array of strings."
    );
  }

  if (!isStringArray(value.curriculum_progress)) {
    errors.push(
      "curriculum_progress must be an array of strings."
    );
  }

  if (typeof value.closing_comment !== "string") {
    errors.push("closing_comment must be a string.");
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

export function parsePenEStudentReportDraft(rawText) {
  if (typeof rawText !== "string") {
    return {
      valid: false,
      data: null,
      errors: [
        "The pasted Pen-E response must be text.",
      ],
    };
  }

  let cleaned = rawText.trim();

  // ----------------------------------------------------------
  // 1. Strip accidental Markdown code fences
  //
  // Handles:
  // ```json
  // { ... }
  // ```
  //
  // and:
  // ```
  // { ... }
  // ```
  // ----------------------------------------------------------

  cleaned = cleaned
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();


  // ----------------------------------------------------------
  // 2. Normalize curly / smart quotation marks
  //
  // “ ” -> "
  // ‘ ’ -> '
  //
  // JSON specifically requires straight double quotes.
  // ----------------------------------------------------------

  cleaned = cleaned
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2018\u2019]/g, "'");


  // ----------------------------------------------------------
  // 3. Extract the JSON object if surrounding prose was pasted
  //
  // Example:
  // Here is the JSON:
  // { ... }
  // Hope this helps.
  //
  // We only extract between the first { and final }.
  // ----------------------------------------------------------

  const firstBrace =
    cleaned.indexOf("{");

  const lastBrace =
    cleaned.lastIndexOf("}");

  if (
    firstBrace !== -1 &&
    lastBrace !== -1 &&
    lastBrace > firstBrace
  ) {
    cleaned = cleaned
      .slice(
        firstBrace,
        lastBrace + 1
      )
      .trim();
  }


  // ----------------------------------------------------------
  // 4. Parse JSON
  // ----------------------------------------------------------

  let parsed;

  try {
    parsed =
      JSON.parse(cleaned);
  } catch (error) {
    return {
      valid: false,
      data: null,
      errors: [
        "The pasted Pen-E response is not valid JSON.",
        error?.message
          ? `JSON error: ${error.message}`
          : null,
      ].filter(Boolean),
    };
  }


  // ----------------------------------------------------------
  // 5. Strict AEOS schema validation
  // ----------------------------------------------------------

  const validation =
    validatePenEStudentReportDraft(
      parsed
    );

  return {
    valid:
      validation.valid,

    data:
      validation.valid
        ? parsed
        : null,

    errors:
      validation.errors,

    cleanedText:
      cleaned,
  };
}

